version: 2

builds:
  - id: "cli-proxy-api"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/server/
    binary: cli-proxy-api
    ldflags:
      - -s -w -X 'main.Version={{.Version}}' -X 'main.Commit={{.ShortCommit}}' -X 'main.BuildDate={{.Date}}'
archives:
  - id: "cli-proxy-api"
    format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
